apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: remo-exporter
  namespace: remo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: remo-exporter
    spec:
      containers:
        - name: remo-exporter
          image: kenfdev/remo-exporter:latest-armhf
          imagePullPolicy: Always
          ports:
            - containerPort: 9352
              protocol: TCP
          env:
            - name: OAUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: remo-secrets
                  key: oauth-token
